apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: coletivocovid19-sim
  name: coletivocovid19-sim
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: coletivocovid19-sim
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: coletivocovid19-sim
    spec:
      containers:
        - image: gcr.io/coletivocovid19/github.com/andrelnunes/covid-19
          imagePullPolicy: IfNotPresent
          name: covid-19-1
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: coletivocovid19-sim
  namespace: default
spec:
  maxReplicas: 2
  metrics:
    - resource:
        name: cpu
        targetAverageUtilization: 80
      type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: coletivocovid19-sim
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: coletivocovid19-sim
  name: coletivocovid19-sim-service
  namespace: default
spec:
  clusterIP: 10.100.6.47
  externalTrafficPolicy: Cluster
  ports:
    - nodePort: 30665
      port: 80
      protocol: TCP
      targetPort: 8501
  selector:
    app: coletivocovid19-sim
  sessionAffinity: None
  type: LoadBalancer
